### ISSUE TITLE
Enhancements

### ISSUE THREAD

**Issue by Hosch250** [Hosch250/CheckersWebsite#6]
## Top Priority
- [ ] API for bots to make moves

## Todo
- [x] Sound on move
- [x] Chat
- [ ] Support user being in multiple tabs
- [ ] Highlight most recent move
- [ ] Move times
- [ ] I18n
- [ ] Authentication
- [ ] Timed games

## Nice-to-have
- [ ]  Animations when move are made
- [ ] Enhanced game over notification
